// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz9wwKL8p4rSIcq3yHXVSZ7cuJngfH8DM',
    appId: '1:123923132495:web:90e14fab4b0e46fa703a3a',
    messagingSenderId: '123923132495',
    projectId: 'my-chat-app-material-3',
    authDomain: 'my-chat-app-material-3.firebaseapp.com',
    storageBucket: 'my-chat-app-material-3.appspot.com',
    measurementId: 'G-FPRQ1JWRY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkItxXEPAhXq8_7PYQx8qx-YB15HpbeYw',
    appId: '1:123923132495:android:995441111f00ea61703a3a',
    messagingSenderId: '123923132495',
    projectId: 'my-chat-app-material-3',
    storageBucket: 'my-chat-app-material-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvoXDIZ6g8i9vyb8L63EFOCmb_3fPoXPQ',
    appId: '1:123923132495:ios:12617ba864c4286f703a3a',
    messagingSenderId: '123923132495',
    projectId: 'my-chat-app-material-3',
    storageBucket: 'my-chat-app-material-3.appspot.com',
    iosBundleId: 'com.example.chatAppMaterial3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvoXDIZ6g8i9vyb8L63EFOCmb_3fPoXPQ',
    appId: '1:123923132495:ios:12617ba864c4286f703a3a',
    messagingSenderId: '123923132495',
    projectId: 'my-chat-app-material-3',
    storageBucket: 'my-chat-app-material-3.appspot.com',
    iosBundleId: 'com.example.chatAppMaterial3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAz9wwKL8p4rSIcq3yHXVSZ7cuJngfH8DM',
    appId: '1:123923132495:web:7da35df4dee2a9a5703a3a',
    messagingSenderId: '123923132495',
    projectId: 'my-chat-app-material-3',
    authDomain: 'my-chat-app-material-3.firebaseapp.com',
    storageBucket: 'my-chat-app-material-3.appspot.com',
    measurementId: 'G-2Q37HPFGJP',
  );
}
